"""
app/db/models.py

SQLAlchemy declarative ORM models — platform layer.
Contains Base, User, and helper utilities.

Domain models (Student, School, etc.) have been extracted to
app.modules.school_choice.models.models and are re-exported below
for backward compatibility.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Helper: timezone-aware UTC now (used as server_default fallback in tests)
# ---------------------------------------------------------------------------


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# users
# REQ-024
# ---------------------------------------------------------------------------


class User(Base):
    """Authenticated counselor account."""

    __tablename__ = "users"

    __table_args__ = (UniqueConstraint("email", name="uq_users_email"),)

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key — UUID generated by PostgreSQL gen_random_uuid()",
    )
    email = Column(
        String(255),
        nullable=False,
        comment="Unique counselor email address; used as login credential",
    )
    hashed_password = Column(
        String,
        nullable=False,
        comment="Bcrypt hash — plaintext is never stored",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT; not modifiable",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at INSERT and UPDATE",
    )

    # v2 additions — REQ-047, REQ-048, REQ-079
    role = Column(
        String(20), nullable=False, default="counsellor",
        server_default="'counsellor'",
        comment="Enum: counsellor | admin. Default: counsellor",
    )
    display_name = Column(
        String(255), nullable=True,
        comment="Editable display name; distinct from email",
    )
    preferred_language = Column(
        String(10), nullable=True, default="en",
        server_default="'en'",
        comment="'en' or 'zh-HK'; default 'en'",
    )
    is_active = Column(
        Boolean, nullable=False, default=True,
        server_default="true",
        comment="true until soft-deleted; row is retained for audit",
    )

    # Relationships
    students = relationship(
        "Student",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!s} email={self.email!r}>"


# ---------------------------------------------------------------------------
# Re-export domain models for backward compatibility (strangler fig)
# These classes now live in app.modules.school_choice.models.models
# ---------------------------------------------------------------------------
from app.modules.school_choice.models.models import (  # noqa: E402, F401
    Student, School, Recommendation, ActionPlan,
)
