"""
app/db/models.py

SQLAlchemy declarative ORM models — platform layer.
Contains Base, User, and helper utilities.

Domain models (Student, School, etc.) have been extracted to
app.modules.school_choice.models.models and are re-exported below
for backward compatibility.
"""

import uuid as _uuid_mod
uuid = _uuid_mod  # backward compat: models reference uuid.uuid4
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    ForeignKey,
    String,
    Text,
    TypeDecorator,
    UniqueConstraint,
    CHAR,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func


# ---------------------------------------------------------------------------
# Portable UUID type — works on both PostgreSQL and SQLite
# ---------------------------------------------------------------------------

class UUID(TypeDecorator):
    """Platform-agnostic UUID type.
    Uses PostgreSQL's native UUID on Postgres, CHAR(32) on SQLite.
    Always returns Python uuid.UUID objects on read.
    """
    impl = CHAR(32)
    cache_ok = True

    def __init__(self, as_uuid=True, *args, **kwargs):
        # Accept as_uuid for backward compat with postgresql UUID usage
        super().__init__(*args, **kwargs)

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=True))
        return dialect.type_descriptor(CHAR(32))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "postgresql":
            return value if isinstance(value, _uuid_mod.UUID) else _uuid_mod.UUID(str(value))
        # SQLite: store as 32-char hex
        if isinstance(value, _uuid_mod.UUID):
            return value.hex
        return _uuid_mod.UUID(str(value)).hex

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if isinstance(value, _uuid_mod.UUID):
            return value
        if isinstance(value, int):
            return _uuid_mod.UUID(int=value)
        if isinstance(value, bytes):
            return _uuid_mod.UUID(bytes=value)
        return _uuid_mod.UUID(str(value))


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Helper: timezone-aware UTC now (used as server_default fallback in tests)
# ---------------------------------------------------------------------------


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# users
# REQ-024
# ---------------------------------------------------------------------------


class User(Base):
    """Authenticated counselor account."""

    __tablename__ = "users"

    __table_args__ = (UniqueConstraint("email", name="uq_users_email"),)

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key — UUID generated by PostgreSQL gen_random_uuid()",
    )
    email = Column(
        String(255),
        nullable=False,
        comment="Unique counselor email address; used as login credential",
    )
    hashed_password = Column(
        String,
        nullable=False,
        comment="Bcrypt hash — plaintext is never stored",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT; not modifiable",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at INSERT and UPDATE",
    )

    # v2 additions — REQ-047, REQ-048, REQ-079
    role = Column(
        String(20), nullable=False, default="counsellor",
        server_default="'counsellor'",
        comment="Enum: counsellor | admin | student. Default: counsellor",
    )
    display_name = Column(
        String(255), nullable=True,
        comment="Editable display name; distinct from email",
    )
    preferred_language = Column(
        String(10), nullable=True, default="en",
        server_default="'en'",
        comment="'en' or 'zh-HK'; default 'en'",
    )
    is_active = Column(
        Boolean, nullable=False, default=True,
        server_default="true",
        comment="true until soft-deleted; row is retained for audit",
    )
    deleted_at = Column(
        TIMESTAMP(timezone=True), nullable=True, default=None,
        comment="Soft delete timestamp — NULL means active",
    )
    student_id = Column(
        UUID(as_uuid=True),
        ForeignKey("students.id", ondelete="SET NULL", name="fk_user_student_id"),
        nullable=True,
        comment="FK to students.id — links student user to their student record",
    )
    must_change_password = Column(
        Boolean, nullable=False, default=False,
        server_default="false",
        comment="Force password change on next login",
    )
    can_manage_cohorts = Column(
        Boolean, nullable=False, default=False,
        server_default="false",
        comment="If true, this teacher can create/edit/delete cohorts",
    )
    reset_token_jti = Column(
        String(36), nullable=True,
        comment="Current password reset token JTI — cleared after use",
    )

    # Relationships
    students = relationship(
        "Student",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
        foreign_keys="[Student.user_id]",
    )
    org_memberships = relationship(
        "OrganisationMembership",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!s} email={self.email!r}>"


# ---------------------------------------------------------------------------
# organisations
# Multi-tenancy: organisations own data, users belong via membership
# ---------------------------------------------------------------------------


class Organisation(Base):
    """An organisation (school, consultancy, etc.) that owns student data."""

    __tablename__ = "organisations"

    __table_args__ = (
        UniqueConstraint("slug", name="uq_organisations_slug"),
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )
    name = Column(String(255), nullable=False, comment="Human-readable organisation name")
    slug = Column(String(255), nullable=False, comment="URL-safe unique identifier")
    is_active = Column(
        Boolean, nullable=False, default=True,
        server_default="true",
        comment="Soft-delete flag; false disables the organisation",
    )
    metadata_ = Column(
        "metadata", Text, nullable=True,
        comment="Free-form metadata (JSON string or plain text)",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
    )

    email_domain = Column(
        String(255), nullable=True,
        comment="Email domain for student accounts",
    )

    # Relationships
    memberships = relationship(
        "OrganisationMembership",
        back_populates="organisation",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Organisation id={self.id!s} slug={self.slug!r}>"


# ---------------------------------------------------------------------------
# organisation_memberships
# ---------------------------------------------------------------------------


class OrganisationMembership(Base):
    """Links a User to an Organisation with a role."""

    __tablename__ = "organisation_memberships"

    __table_args__ = (
        UniqueConstraint(
            "organisation_id", "user_id",
            name="uq_org_membership_org_user",
        ),
        CheckConstraint(
            "role IN ('owner', 'admin', 'member')",
            name="ck_org_membership_role",
        ),
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )
    organisation_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organisations.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    role = Column(
        String(20), nullable=False, default="member",
        server_default="'member'",
        comment="owner | admin | member",
    )
    permission = Column(
        String(20), nullable=False, default="read_write",
        server_default="'read_write'",
        comment="Global permission: read_write | read_only. Counsellors default read_write.",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
    )

    # Relationships
    organisation = relationship("Organisation", back_populates="memberships")
    user = relationship("User", back_populates="org_memberships")

    def __repr__(self) -> str:
        return (
            f"<OrganisationMembership id={self.id!s} "
            f"org={self.organisation_id!s} user={self.user_id!s} role={self.role!r} perm={self.permission!r}>"
        )


# ---------------------------------------------------------------------------
# registration_tokens — single-use tokens for admin registration
# ---------------------------------------------------------------------------


class RegistrationToken(Base):
    """Single-use token for admin registration."""
    __tablename__ = "registration_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    token = Column(String(64), unique=True, index=True, nullable=False)
    organisation_id = Column(UUID(as_uuid=True), ForeignKey("organisations.id"), nullable=False)
    consumed_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    consumed_at = Column(TIMESTAMP(timezone=True), nullable=True)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now(), default=_utcnow)


# ---------------------------------------------------------------------------
# teacher_groups — named groups of teachers within an organisation
# ---------------------------------------------------------------------------


class TeacherGroup(Base):
    __tablename__ = "teacher_groups"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    organisation_id = Column(UUID(as_uuid=True), ForeignKey("organisations.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now(), default=_utcnow)
    updated_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now(), default=_utcnow)
    members = relationship("TeacherGroupMember", back_populates="group", cascade="all, delete-orphan")
    permissions = relationship("CohortPermission", back_populates="group", cascade="all, delete-orphan")


class TeacherGroupMember(Base):
    __tablename__ = "teacher_group_members"
    __table_args__ = (UniqueConstraint("group_id", "user_id", name="uq_tgm_group_user"),)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    group_id = Column(UUID(as_uuid=True), ForeignKey("teacher_groups.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    group = relationship("TeacherGroup", back_populates="members")


# ---------------------------------------------------------------------------
# cohort_permissions — group-based per-cohort access control
# ---------------------------------------------------------------------------


class CohortPermission(Base):
    __tablename__ = "cohort_permissions"
    __table_args__ = (UniqueConstraint("group_id", "cohort_id", name="uq_cohort_perm_group_cohort"),)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid())
    group_id = Column(UUID(as_uuid=True), ForeignKey("teacher_groups.id", ondelete="CASCADE"), nullable=False)
    cohort_id = Column(UUID(as_uuid=True), ForeignKey("student_cohorts.id", ondelete="CASCADE"), nullable=False)
    visible = Column(Boolean, nullable=False, default=True, server_default="true")
    programme_choices = Column(String(10), nullable=False, default="read_write", server_default="'read_write'")
    grades = Column(String(10), nullable=False, default="read_write", server_default="'read_write'")
    plan_generation = Column(String(10), nullable=False, default="read_write", server_default="'read_write'")
    submissions = Column(String(10), nullable=False, default="read_write", server_default="'read_write'")
    reports = Column(String(10), nullable=False, default="read_only", server_default="'read_only'")
    cohort_management = Column(String(10), nullable=False, default="none", server_default="'none'")
    data_import = Column(String(10), nullable=False, default="none", server_default="'none'")
    account_assignment = Column(String(10), nullable=False, default="none", server_default="'none'")
    student_delete = Column(String(10), nullable=False, default="none", server_default="'none'")
    student_profile = Column(String(10), nullable=False, default="none", server_default="'none'")
    group = relationship("TeacherGroup", back_populates="permissions")


# ---------------------------------------------------------------------------
# Re-export domain models for backward compatibility (strangler fig)
# These classes now live in app.modules.school_choice.models.models
# ---------------------------------------------------------------------------
from app.modules.school_choice.models.models import (  # noqa: E402, F401
    Student, School, Recommendation, ActionPlan,
)
