"""
app/db/models.py

SQLAlchemy declarative ORM models for the Intelligent Academic Advisor.
Maps to the schema defined in schema_spec.md.

Tables:
    users
    students
    schools
    recommendations
    action_plans
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy import JSON as JSONB
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Helper: timezone-aware UTC now (used as server_default fallback in tests)
# ---------------------------------------------------------------------------


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# users
# REQ-024
# ---------------------------------------------------------------------------


class User(Base):
    """Authenticated counselor account."""

    __tablename__ = "users"

    __table_args__ = (UniqueConstraint("email", name="uq_users_email"),)

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key — UUID generated by PostgreSQL gen_random_uuid()",
    )
    email = Column(
        String(255),
        nullable=False,
        comment="Unique counselor email address; used as login credential",
    )
    hashed_password = Column(
        String,
        nullable=False,
        comment="Bcrypt hash — plaintext is never stored",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT; not modifiable",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at INSERT and UPDATE",
    )

    # v2 additions — REQ-047, REQ-048, REQ-079
    role = Column(
        String(20), nullable=False, default="counsellor",
        server_default="'counsellor'",
        comment="Enum: counsellor | admin. Default: counsellor",
    )
    display_name = Column(
        String(255), nullable=True,
        comment="Editable display name; distinct from email",
    )
    preferred_language = Column(
        String(10), nullable=True, default="en",
        server_default="'en'",
        comment="'en' or 'zh-HK'; default 'en'",
    )
    is_active = Column(
        Boolean, nullable=False, default=True,
        server_default="true",
        comment="true until soft-deleted; row is retained for audit",
    )

    # Relationships
    students = relationship(
        "Student",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!s} email={self.email!r}>"


# ---------------------------------------------------------------------------
# students
# REQ-025, REQ-028
# ---------------------------------------------------------------------------


class Student(Base):
    """Student profile managed by a counselor."""

    __tablename__ = "students"

    __table_args__ = (
        CheckConstraint(
            "target_region IN ('local', 'international')",
            name="ck_students_target_region",
        ),
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key",
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE", name="fk_students_user_id"),
        nullable=False,
        index=True,
        comment="Owning counselor — FK to users.id, cascade delete",
    )
    name = Column(
        String(255),
        nullable=False,
        comment="Student full name",
    )
    grades = Column(
        JSONB,
        nullable=False,
        server_default="{}",
        default=dict,
        comment='Map of subject (string) to grade value (string). E.g. {"math": "A"}',
    )
    interests = Column(
        JSONB,
        nullable=False,
        server_default="[]",
        default=list,
        comment='Array of interest tag strings. E.g. ["robotics", "music"]',
    )
    strengths_weaknesses = Column(
        Text,
        nullable=False,
        server_default="''",
        default="",
        comment="Free-text; may be empty string but not NULL",
    )
    target_region = Column(
        String(50),
        nullable=False,
        comment="Constrained to 'local' or 'international'",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at INSERT and UPDATE",
    )

    # v2 additions — REQ-057
    preferred_name = Column(
        String(255), nullable=True,
        comment="Preferred/display name distinct from full name",
    )
    date_of_birth = Column(
        Date, nullable=True,
        comment="PII — encrypted at rest (ADR-008)",
    )
    gender = Column(
        String(20), nullable=True,
        comment="Free text",
    )
    address = Column(
        Text, nullable=True,
        comment="PII — encrypted at rest (ADR-008)",
    )
    phone = Column(
        String(50), nullable=True,
        comment="PII — encrypted at rest (ADR-008)",
    )
    email = Column(
        String(255), nullable=True,
        comment="Student contact email; distinct from counsellor account email",
    )
    class_name = Column(
        String(50), nullable=True,
        comment="E.g. '5A'",
    )
    year_of_study = Column(
        Integer, nullable=True,
        comment="Academic year",
    )
    candidate_number = Column(
        String(50), nullable=True,
        comment="HKDSE candidate number",
    )
    preferred_language = Column(
        String(10), nullable=True, default="en",
        server_default="'en'",
        comment="'en' or 'zh-HK'",
    )
    ielts_score = Column(
        JSONB, nullable=True,
        comment=(
            "Full IELTS score object: "
            "{overall, listening, reading, writing, speaking, test_date}"
        ),
    )
    other_language_scores = Column(
        JSONB, nullable=True,
        comment="Array: [{label, score, date}]",
    )
    teacher_evaluation = Column(
        JSONB, nullable=True,
        comment="Array: [{subject_code, teacher_name, rating, comment, date}]",
    )
    extra_curricular = Column(
        JSONB, nullable=True,
        comment="Array: [{activity, role, years, achievement}]",
    )
    awards = Column(
        JSONB, nullable=True,
        comment="Array: [{title, awarding_body, level, year}]",
    )
    financial_aid_flag = Column(
        Boolean, nullable=True, default=False,
        server_default="false",
        comment="True if the student is applying for financial aid",
    )
    notes = Column(
        Text, nullable=True,
        comment="Counsellor free-text notes",
    )
    # Added via ALTER TABLE — must also be declared here so ORM can read them
    personal_statement = Column(Text, nullable=True)
    is_graduated = Column(Boolean, nullable=True, default=False, server_default="false")
    graduation_year = Column(Integer, nullable=True)
    final_school_id = Column(UUID(as_uuid=True), ForeignKey("schools.id", ondelete="SET NULL", name="fk_students_final_school_id"), nullable=True, index=True)
    final_major = Column(String(255), nullable=True)

    # Relationships
    user = relationship("User", back_populates="students")
    recommendations = relationship(
        "Recommendation",
        back_populates="student",
        cascade="all, delete-orphan",
        lazy="select",
    )
    action_plan = relationship(
        "ActionPlan",
        back_populates="student",
        cascade="all, delete-orphan",
        uselist=False,
        lazy="select",
    )
    # v2 relationships (back_populates targets defined in models_v2.py)
    subject_grades = relationship(
        "StudentSubjectGrade",
        back_populates="student",
        cascade="all, delete-orphan",
        lazy="select",
    )
    transcripts = relationship(
        "Transcript",
        back_populates="student",
        cascade="all, delete-orphan",
        lazy="select",
    )
    school_targets = relationship(
        "StudentSchoolTarget",
        back_populates="student",
        cascade="all, delete-orphan",
        lazy="select",
    )
    plan_jobs = relationship(
        "PlanGenerationJob",
        back_populates="student",
        cascade="all, delete-orphan",
        lazy="select",
    )
    academic_plan = relationship(
        "AcademicPlan",
        back_populates="student",
        cascade="all, delete-orphan",
        uselist=False,
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Student id={self.id!s} name={self.name!r} user_id={self.user_id!s}>"


# ---------------------------------------------------------------------------
# schools
# REQ-026, REQ-030
# ---------------------------------------------------------------------------


class School(Base):
    """School record in the system's internal catalog."""

    __tablename__ = "schools"

    __table_args__ = (UniqueConstraint("name", name="uq_schools_name"),)

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key",
    )
    name = Column(
        String(255),
        nullable=False,
        comment="Unique school name",
    )
    location = Column(
        String(255),
        nullable=False,
        comment="Geographic location string",
    )
    min_academic_requirements = Column(
        JSONB,
        nullable=False,
        server_default="{}",
        default=dict,
        comment='Map of subject to minimum grade. E.g. {"math": "B"}',
    )
    key_strengths = Column(
        JSONB,
        nullable=False,
        server_default="[]",
        default=list,
        comment='Array of strength tag strings. E.g. ["STEM", "arts"]',
    )
    notes = Column(
        Text,
        nullable=True,
        comment="Optional free-text notes; nullable",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at INSERT and UPDATE",
    )

    # Added via ALTER TABLE
    is_custom = Column(Boolean, nullable=True, default=False, server_default="false")
    major_requirements = Column(JSONB, nullable=True)

    # v2 additions — REQ-058
    name_zh = Column(
        String(255), nullable=True,
        comment="Chinese name of the school",
    )
    type = Column(
        String(30), nullable=True,
        server_default="'UNIVERSITY'",
        comment="Enum: UNIVERSITY | POLYTECHNIC | COMMUNITY_COLLEGE | VOCATIONAL",
    )
    website = Column(
        String(500), nullable=True,
        comment="School website URL",
    )
    description = Column(
        Text, nullable=True,
        comment="School description",
    )
    minimum_entry_score = Column(
        Integer, nullable=True,
        comment="HKDSE best-5 aggregate threshold for admission",
    )
    required_subjects = Column(
        JSONB, nullable=True,
        comment="Array: [{subject_code, min_grade}]",
    )
    language_requirements = Column(
        JSONB, nullable=True,
        comment="E.g. {ielts_minimum: 6.5}",
    )
    faculties = Column(
        JSONB, nullable=True,
        comment="Array of faculty name strings",
    )
    notable_programs = Column(
        JSONB, nullable=True,
        comment="Array of program description strings",
    )
    acceptance_rate = Column(
        Numeric(5, 4), nullable=True,
        comment="Admission acceptance rate 0.0000–1.0000",
    )
    average_admitted_score = Column(
        Numeric(5, 2), nullable=True,
        comment="JUPAS median admitted HKDSE aggregate score",
    )
    scholarship_available = Column(
        Boolean, nullable=True, default=False,
        server_default="false",
        comment="True if scholarship opportunities exist",
    )
    data_source = Column(
        Text, nullable=True,
        comment="Source URL or reference for school profile data",
    )
    data_last_updated = Column(
        Date, nullable=True,
        comment="Date the school profile data was last refreshed",
    )

    # Relationships
    recommendations = relationship(
        "Recommendation",
        back_populates="school",
        lazy="select",
        # No cascade: school deletion does not cascade to recommendations.
    )
    student_targets = relationship(
        "StudentSchoolTarget",
        back_populates="school",
        lazy="select",
        # No cascade: school deletion is RESTRICTED by FK on student_school_targets
    )

    def __repr__(self) -> str:
        return f"<School id={self.id!s} name={self.name!r}>"


# ---------------------------------------------------------------------------
# recommendations
# REQ-027, REQ-029
# ---------------------------------------------------------------------------


class Recommendation(Base):
    """
    A single matched school result for a student.

    At most 5 rows per student at any time (REQ-019).
    The POST recommendations endpoint deletes all existing rows for the
    student before inserting new ones.
    """

    __tablename__ = "recommendations"

    __table_args__ = (
        UniqueConstraint(
            "student_id",
            "rank",
            name="uq_recommendations_student_rank",
        ),
        CheckConstraint(
            "score >= 0 AND score <= 100",
            name="ck_recommendations_score",
        ),
        CheckConstraint(
            "rank >= 1 AND rank <= 5",
            name="ck_recommendations_rank",
        ),
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key",
    )
    student_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "students.id",
            ondelete="CASCADE",
            name="fk_recommendations_student_id",
        ),
        nullable=False,
        index=True,
        comment="FK to students.id, cascade delete",
    )
    school_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "schools.id",
            name="fk_recommendations_school_id",
        ),
        nullable=False,
        comment="FK to schools.id — no cascade on school delete",
    )
    school_name = Column(
        String(255),
        nullable=False,
        comment="Denormalized copy of schools.name at generation time",
    )
    score = Column(
        Numeric(5, 2),
        nullable=False,
        comment="Computed match score 0–100 (NUMERIC 5,2); API layer converts to 0.0–1.0",
    )
    explanation = Column(
        Text,
        nullable=False,
        comment="Plain-text rationale generated by the matching engine",
    )
    gaps = Column(
        Text,
        nullable=False,
        comment="Plain-text student deficiency description generated by the matching engine",
    )
    rank = Column(
        Integer,
        nullable=False,
        comment="Ordinal rank within this student's set (1 = highest); constrained 1–5",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT; replaced on each generate run",
    )

    # Relationships
    student = relationship("Student", back_populates="recommendations")
    school = relationship("School", back_populates="recommendations")

    def __repr__(self) -> str:
        return (
            f"<Recommendation id={self.id!s} student_id={self.student_id!s} "
            f"school_name={self.school_name!r} rank={self.rank} score={self.score}>"
        )


# ---------------------------------------------------------------------------
# action_plans
# REQ-025 (student-owned output), REQ-027 (generated artifact)
# ---------------------------------------------------------------------------


class ActionPlan(Base):
    """
    Action plan generated for a student.

    Enforces one-plan-per-student via UNIQUE on student_id.
    Re-generating replaces the existing row (UPSERT).
    """

    __tablename__ = "action_plans"

    __table_args__ = (UniqueConstraint("student_id", name="uq_action_plans_student_id"),)

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
        comment="Primary key",
    )
    student_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "students.id",
            ondelete="CASCADE",
            name="fk_action_plans_student_id",
        ),
        nullable=False,
        comment="FK to students.id, cascade delete; UNIQUE enforces one plan per student",
    )
    academic_targets = Column(
        Text,
        nullable=False,
        comment="Plain-text academic improvement targets",
    )
    extracurricular_direction = Column(
        Text,
        nullable=False,
        comment="Plain-text suggested extracurricular focus",
    )
    preparation_steps = Column(
        Text,
        nullable=False,
        comment="Plain-text general preparation guidance",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=_utcnow,
        comment="Set at INSERT",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        default=_utcnow,
        comment="Set at UPDATE (replace on re-generate)",
    )

    # Relationships
    student = relationship("Student", back_populates="action_plan")

    def __repr__(self) -> str:
        return f"<ActionPlan id={self.id!s} student_id={self.student_id!s}>"
