#!/usr/bin/env bash
set -euo pipefail

OUT="${1:-.env}"

if ! command -v openssl &>/dev/null; then
  echo "Error: openssl not found. Install it or use: python3 -c \"import secrets; print(secrets.token_hex(32))\""
  exit 1
fi

SECRET_KEY=$(openssl rand -hex 32)

cat > "$OUT" <<EOF
# Generated by scripts/generate_secrets.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Fill in CHANGE_ME values before starting the app.

# === REQUIRED (app will not start without these) ===
DATABASE_URL=CHANGE_ME
SECRET_KEY=${SECRET_KEY}

# === AUTH ===
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# === CORS ===
# Comma-separated list of allowed origins (your Vercel URL + any custom domain)
CORS_ORIGINS=CHANGE_ME

# === AI Provider (optional — AI features degrade gracefully without these) ===
AI_PROVIDER=gemini
AI_API_KEY=
# AI_MODEL=
# AI_BASE_URL=
# AI_TIMEOUT=30
EOF

echo "Generated: ${OUT}"
echo "  SECRET_KEY: set ($(echo -n "$SECRET_KEY" | wc -c | tr -d ' ') hex chars)"
echo ""
echo "  Next steps:"
echo "    1. Set DATABASE_URL to your Neon connection string (with ?sslmode=require)"
echo "    2. Set CORS_ORIGINS to your Vercel deployment URL"
echo "    3. Optionally set AI_API_KEY for AI features"
